### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by aredridel**
s/tbergeron/brainpad/

### CODE REVIEW

**Comment by tbergeron** [comment]
Thanks for this, totally forgot to change that when I switched ownership.

**Comment by aredridel** [comment]
You're welcome!

**Comment by tbergeron** [comment]
I don't know if you're trying out the framework, but if you need any help or explanation about it do not hesitate to open an issue about it. :-)

**Comment by aredridel** [comment]
Awesome. I'm poking at it with my usual interest in frameworks in general.

**Pull request merged**
